### ISSUE TITLE
Run linux on Cardputer?

### ISSUE THREAD

**Issue by altgreen64** [echo-lalia/Cardputer-MicroHydra#32]
Can we run linux on Cardputer?
[yt](https://www.youtube.com/watch?v=pj0a91vlcGo)

**Comment by echo-lalia** [comment]
Unfortunately, I think that the Cardputer probably wouldn't have enough ram to run a full Linux distro. 

There were some people talking about it in the Cardputer discord, but basically determined that it might not be possible. 

If it is possible, I'll be interested to see it. But it's not something I have the skills or an interest in trying to build myself.
