### ISSUE TITLE
Adding support for Daylight Saving Time Adjustment

### ISSUE THREAD

**Issue by swagatpanda** [echo-lalia/Cardputer-MicroHydra#33]
Hi , 

Amazing library, made my entry into the world of MicroPython so easy.

Can I tinker with the code to add an option in the settings menu to enable Daylight Saving Time ?

You can let me know if that is the right way to do it or you have something else in mind

**Comment by echo-lalia** [comment]
Feel free to tinker with the code however you'd like. If you've added a feature, or improved it in some way, and want to share, submit a pull request, and I'll merge it into the project (unless it breaks something else, of course) 😊

The current timezone logic is extremely 'naive'; it literally just adds or subtracts some number from the current hour. Adding support for daylight savings time is gonna require expanding that logic somewhat. 

Also! I'm in the middle of completely rewriting the settings app with the help of a new module called "HydraMenu". The old settings app code straight-up sucks and it's really annoying to edit. Please don't waste your time trying to tinker with that. The new settings app is in the "settings-overhaul" branch, and it should be very easy to add a new settings option there 😁

**Comment by swagatpanda** [comment]
I'll check the settings-overhaul branch in that cases 👍
